package fauzi.hilmy.app18;

import java.util.ArrayList;

public class PoisonData {
    public static String[][] dataTanaman = new String[][]{
            {"1. Tanaman Jarak","https://storage.googleapis.com/bbc.dosenbiologi.com/2016/01/Tanaman-Jarak-300x225.jpg","Tanaman ini sudah tercatat di rekor dunia sebagai tanaman beracun yang sangat mematikan. Tanaman yang dikenal juga sebagai tanaman cator ini berbahaya pada bijinya. Daun dan getah jarak biasanya banyak digunakan untuk pengobatan tradisional, tapi siapa sangka biji jarak adalah pembunuh yang mematikan. Memakan dua biji jarak sudah cukup menamatkan riwayat hidup anda selamanya.\n" +
                    "\n" +
                    "Biji tanaman jarak ini mengandung racun yang bisa menyebabkan rasa terbakar pada mulut, leher, perut dan selanjutnya bisa mengakibatkan kematian karena dehidrasi. Racun yang terkandung dalam pengolahan biji jarak ini biasa dikenal dengan ricin. Ricin merupakan senyawa sampingan yang dihasilkan dari pengolahan biji tanaman jarak. Senyawa ini dapat mengakibatkan orang tewas karena menyebabkan gangguan sistem peredaran darah dan pernafasan. Saat ricin masuk dalam tubuh, satu molekul ricin akan membunuh satu sel. Jika senyawa ini terhirup, disuntikkan atau tertelan, kurang dari titik kecil ricin dapat membunuh seseorang dalam waktu 36-48 jam.Para ahli medis mengatakan, ricin merupakan pembunuh ganas sekuat virus anthrax. Dan, bahayanya lagi, sampai saat ini belum ditemukan penawarnya."},
            {"2. Ubi Racun atau Singkong Karet","https://storage.googleapis.com/bbc.dosenbiologi.com/2016/01/Ubi-Racun-atau-Singkong-Karet-300x204.jpg","Singkong atau dikenal juga dengan ubi memang makanan khas desa yang banyak digemari masyarakat. Tetapi siapa sangka ternyata singkong itu mengandung racun yang berbahaya. Namun, kadarnya berbeda bergantung varietasnya. Singkong pahit yang memiliki nama latin Manihot glaziovii (dikenal sebagai ubi racun atau singkong karet) kadar racunnya jauh lebih tinggi dibanding singkong manis yang biasa dikonsumsi setiap hari (Manihot utilissima). Racun yang ada pada singkong biasanya terkonsentrasi di daun dan umbi singkong, racun itu diketahui sebagai senyawa cyanogenik glycoside; linamarin dan lotaustralin yang oleh enzim dapat menghasilkan asam sianida.\n" +
                    "\n" +
                    "Sianida dikenal sebagai pembunuh berdarah dingin dan sulit terditeksi, ia tidak berasa, tidak berbau dan tidak berwarna. Satu-satunya indikator untuk mengetahui sianida ada pada singkong adalah warna kebiruan yang muncul pada umbi bila lama terpapar udara.Racun sianida akan jauh berkurang bila dipanaskan. Biasanya korban yang keracunan akibat salah dalam pengolahan singkong karena memasak umbi atau daun tidak sempurna. Jadi, bagi anda yang sudah tahu hal ini jangan pernah memakan daun atau umbi singkong dalam keadaan mentah atau setengah matang karena itu sangat berbahaya."},
            {"3. Kecubung (Datura Metel)","https://storage.googleapis.com/bbc.dosenbiologi.com/2016/01/Kecubung-Datura-Metel-300x225.jpg","Tanaman kecubung yang ada di Indonesia ini berjenis Datura Metel, dan masih satu keluarga dengan Bunga Lonceng. Sebenernya kecubung mengandung senyawa kimia yang memiliki banyak khasiat menyembuhkan berbagai macam penyakit. Kandungan ini membuat kecubung dapat dimanfaatkan sebagai obat tradisional untuk berbagai penyakit, seperti asma, reumatik, sakit pinggang, pegel linu, bisul maupun eksim, sakit gigi, ketombe, hingga nyeri haid. Bagian tanaman kecubung yang paling sering dipakai sebagai obat herbal ini adalah daun.\n" +
                    "\n" +
                    "Namun, jangan dikira tanaman kecubung aman-aman saja. Anda perlu tahu, kecubung juga mengandung racun berupa zat alkaloid yang mempunyai efek halusinogen terutama pada bagian bijinya. Efek yang ditimbulkan bila kecubung yang dikonsumsi melebihi takaran antara lain mual, muntah, sesak nafas, rasa gelisah, nadi berdenyut cepat, kulit wajah dan tubuh berubah menjadi merah, pusing, mulut terasa kaku, halusinasi hingga akhirnya berujung pada kematian. Dalam beberapa kasus penggunaan racun biji kecubung biasanya digunakan untuk bunuh diri."},
            {"4. Pohon Upas","https://storage.googleapis.com/bbc.dosenbiologi.com/2016/01/pohon-opas-300x196.jpg","Nama ilmiah dari pohon upas ini adalah Antiaris toxicaria , di indonesia pohon ini masih banyak ditemukan, di pulau jawa pohon upas ini dikenal dengan sebutan pohon Ancar. Pohon Upas atau pohon Ancar ini pernah menjadi momok menakutkan dan begitu legendaris pada masa penjajahan VOC di Nusantara. Pasalnya tentara VOC pernah dibuat kalang kabut menghadapi perlawanan rakyat yang memakai racun pohon Upas sebagai senjata. Hingga secara khusus Letnan Gubernur Thomas Stamford Raffles (1781-1826) mengutus Thomas Horsfield (1773-1859), naturalis asal Amerika Serikat, untuk mempelajari racun pohon upas ini.\n" +
                    "\n" +
                    "Hasil dari penelitian itu menyatakan bahwa pohon upas memang mematikan, tapi hanya lendir getahnya. Efek racun pohon upas itu cukup mengejutkan kala diuji cobakan kepada seekor ayam dan anjing, yang pertama langsung mati kurang dari dua menit dan yang satunya dalam sekitar delapan menit. Dalam laporannya pada 1812, Horsfield mengutarakan bahwa penduduk lokal sudah menyadari khasiat racun pohon upas untuk keperluan membunuh lawan-lawannya. Sekali terkena getah racunnya, orang tersebut akan kejang-kejang lalu mati."},
            {"5. Gympie-Gympie (Dendrocnide moroides)","https://storage.googleapis.com/bbc.dosenbiologi.com/2016/01/Gympie-GympieDendrocnide-moroides-300x197.jpg","Gympie-gimpie ini tumbuh subur di Hutan Maluku-Indonesia dan hutan timur Australia. Bila anda masuk hutan berhati-hatilah dengan tanaman yang satu ini, bila kebetulan menjumpainya segeralah menjauh, berada didekatnya sama saja mengundang bahaya. Namanya memang sekilas terdengar imut tapi anda jangan terkecoh, ternyata racunnya mematikan.\n" +
                    "\n" +
                    "Orang luar negeri biasanya menyebut gympie-gympie dengan sebutan tanaman penyengat, karena bila kulit tersentuh daun gympie-gympie sedikit saja, rasanya seperti disengat oleh panas luar biasa dan tidak akan hilang hingga berbulan-bulan, karena efek racun moroidin yang terdapat di bulu tanaman ini.Rekor terbesar gympie-gympie adalah pernah membunuh hewan dan manusia. Bahkan Saking kuat racunnya, daun gympie-gympie yang telah kering beratus tahunpun masih mengandung racun moroidin dengan kuat. Dengan efek racun yang begitu luar biasa, tentara Inggris pada akhir tahun 1960an, diduga pernah tertarik pada Gympie-Gympie dan berniat menjadikannya senjata biologis."},
            {"6. Deadly Nightshade","https://storage.googleapis.com/bbc.dosenbiologi.com/2016/01/Deadly-Nightshade-....jpg","Secara sekilas tanaman ini terlihat tidak berbahaya bahkan terlihat dapat dimakan dengan buah berrynya yang berwarna hijau atau hitam mengkilat, ditambah lagi rasa mereka yang manis. Sayangnya, tumbuhan Deadly Nightshade ini adalah salah satu tanaman paling mematikan yang ada di dunia.Racun yang terkandung dari tanaman ini adalah Atropine dan scopolamine yang diproduksi alami oleh sel suatu organisme. Anehnya adalah racun atropine dan scopolamine yang ada di dalam tanaman ini tidak mempengaruhi hewan tertentu seperti kuda, kelinci, domba, dan beberapa burung diketahui tidak terpengaruh oleh racun mereka.\n" +
                    "\n" +
                    "Sementara manusia sendiri sangat sensitif terhadap racun ini, dimana 2 buah berry tanaman ini diketahui cukup untuk membunuh seorang anak kecil, dan 10 hingga 20 buah cukup untuk membunuh seorang manusia dewasa. Hal ini berlaku lebih fatal lagi untuk daun mereka, yakni hanya dibutuhkan 1 daun untuk membunuh seorang pria dewasa. Dan hal yang lagi-lagi aneh, ternyata keluarga dari nightshade ini ternyata begitu dekat dengan dapur kita. Seperti tomat, terong, kentang dan cabai rawit"},
            {"7. Bunga Oleander","https://storage.googleapis.com/bbc.dosenbiologi.com/2016/01/Bunga-Oleander-300x251.jpg","Tanaman Oleander memang cantik, bahkan sering dijadikan penghias halaman sekolah maupun taman. Tetapi anda jangan terkecoh dengan paras cantikanya, karena siapa sangka, bunga oleander termasuk jenis tanaman yang dengan mudah menghilangkan nyawa manusia.\n" +
                    "\n" +
                    "Walaupun tanaman ini indah untuk dilihat, ingatlah untuk jangan pernah memasukkan bagian apapun dari tanaman ini ke mulut Anda. Dimulai dari daun hingga buahnya. Karena Bunga Oleander ini selain dikenal cantik, juga sebagai salah-satu dari tumbuhan yang paling beracun. Jika daunnya di konsumsi satu helai saja dapat membunuh manusia dewasa. Bahkan berdasarakan TESS atau Toxic Exposure Surveillance System, dilaporkan khususnya di Amerika Serikat terdapat 847 jenis racun manusia dan semua racun itu sangat berkaitan dengan bunga Oleander ini."},
            {"8. Rosary Pea atau Rosary Kacang Polong","https://storage.googleapis.com/bbc.dosenbiologi.com/2016/01/Rosary-Pea-atau-Rosario-Kacang-Polong.jpg","Salah satu ciri dari tanaman ini adalah warna merah pada bijinya. Memilik nama lain The Rosary Pea, Crab’s Eye, atau Jumbie Bead. Jika tidak tahu dan dipandang sekilas, tanaman ini nampak tidak berbahaya bahkan terkesan lucu dan unik. Namun ternyata ia memamg mematikan. Sesuai namanya, tumbuhan ini dulu kerap digunakan sebagai manik-manik untuk rosario. Perhiasan di seluruh dunia memakainya. Sehingga banyak pembuat perhiasan yang kondisinya drop bahkan meninggal pasca menusukkan jari ketika memegang tumbuhan ini.\n" +
                    "\n" +
                    "Di Indonesia sendiri tanaman ini dikenal sebagai Saga Rambat. jika anda menghirup dan mengkonsumsinya, maka alamat hidup anda bisa berakhir. Karena Racun yang terkandung dalam tumbuhan ini adalah Abrin yang merupakan salah satu toksin paling mematikan di dunia, gejala awal yang akan ditimbulkan, halusinasi, gagal ginjal dehidrasi dan akhirnya berujung pada kematian."},
            {"9. Doll’s Eye atau Mata Boneka","https://storage.googleapis.com/bbc.dosenbiologi.com/2016/01/Doll%E2%80%99s-Eye-atau-Mata-Boneka-2-300x169.jpg","Penampilan dari tanaman mata boneka ini cukup unik tapi mengerikan, itu wajar karena yang terkandung di dalamnya juga sesuatu yang mengerikan. Titik hitam yang ada di tengah buah berry putih ini adalah titik yang menandakan tempat dengan konsentrat racun tertinggi. Karena bentuknya yang sangat unik inilah biasanya anak kecil suka tertarik dengan tanaman Doll’s Eye. Beberapa kasus anak-anak akan keracunan setelah bermain dengan tanaman ini.\n" +
                    "\n" +
                    "Biji dari tanaman mata boneka ini mengandung toksin cardiogenic. Toksin yang satu ini bisa memberi efek seperti penenang pada jaringan otot jantung. Jika biji tanaman ini  dikonsumsi maka dapat menimbulkan keracunan hingga gagal jantung yang bisa menyebabkan kematian."},
            {"10. Water Hemlock","https://storage.googleapis.com/bbc.dosenbiologi.com/2016/01/Water-Hemlock-1.jpg","Water Hamlok terkenal sebagai salah satu tumbuhan paling mematikan dalam sejarah manusia sejak dulu. Ia ini naik pamor dan menjadi sangat terkenal setelah ia bertanggung jawab atas kematian socrates. Cicuta atau Water Hemlock merupakan tanaman atraktif dengan bunga kecil berwarna putih atau hijau yang teratur menyerupai payung. Di Amerika Utara, Water Hemlock adalah tumbuhan paling mematikan karena sangat beracun bagi manusia.\n" +
                    "\n" +
                    "Tanaman ini kerap dijuluki daun peterseli beracun, bubur setan atau berang-berang beracun. Menjadi sangat beracun, karena semua bagian dalam dirinya memiliki alkaloid coniine, menghasilkan racun cicutoxin. Mereka yang bernasib buruk karena mengkonsumsi water hemlock, secara otomatis Racun Cicutoxin akan aktif dan mengakibatkan kram, muntah-muntah, gemetar, gagal jantung, bahkan melumpuhkan syaraf pusat sebelum akhirnya merenggang nyawa."},
            {"11. The Suicide Tree","https://storage.googleapis.com/bbc.dosenbiologi.com/2016/01/The-Suicide-Tree-300x225.jpg","The Suicide Tree (Pohon Bunuh Diri), Pong-pong, Othalanga, semuanya adalah sebutan untuk 1 spesies pohon yang memilki nama ilmiah Cerbera Odollam. Bentuknya sendiri sangatlah mirip dengan bunga Oleander karena berasal dari famili yang sama. Sedangkan alasan dari penamaan tanaman ini adalah karena tanaman ini adalah tanaman popular untuk senjata pembunuhan diam-diam dan juga bunuh diri.\n" +
                    "\n" +
                    "Tanaman ini mempunyai bagian bagian bunga putih seperti melati namun lebih besar. Racun yang terkandung dalam tanaman ini adalah Cerberin yang dapat menyebabkan gangguan otot jantung, kegagalan pernapasan, dan kemudian kematian. Selain itu, membuat seseorang memakan biji beracun ini juga sangatlah mudah karena rasanya dapat ditutupi oleh bumbu makanan lainnya dan tidak hanya itu saja, racun dari tumbuhan ini sering diabaikan saat otopsi. Inilah sebabnya mengapa The Suicide Tree sering dikatakan sebagai alat pembunuhan yang sempurna."},
            {"12. Aconitum atau Wolf’s bane","https://storage.googleapis.com/bbc.dosenbiologi.com/2016/01/Aconitum-atau-Wolf%E2%80%99s-bane.jpg","Tanaman dengan nama lain seperti wolf’s bane, women’s bane, devils helmet, leopard’s bane, hingga blue rocket adalah nama-nama yang semuanya merujuk ke tumbuhan satu ini. Sering digunakan oleh suku Ainu dari Jepang untuk berburu dengan dioleskan ke ujung panah mereka.\n" +
                    "\n" +
                    "Tumbuhan biasa hidup di daerah pegunungan belahan bumi bagian utara. Ia memiliki racun berbahaya yang dikenal  alkaloid pseudaconitine. Jika anda mengkonsumsi tanaman ini dalam jumlah besar akan menyebabkan kematian setelah 2 hingga 6 jam. Maka Wolsbane termasuk juga kategori tumbuhan beracun yang mematikan. Namun, diketahui hanya 20ml racun ini saja juga dapat membunuh seorang pria dewasa. Nama wolf’s bane dari tumbuhan mematikan ini sendiri berasal dari sejarahnya karena sering digunakan untuk membunuh serigala."},
            {"13. Pohon Strychnine","https://storage.googleapis.com/bbc.dosenbiologi.com/2016/01/Pohon-Strychnine-300x207.jpg","Dikenal sebagai kacang beracun, Pohon Strychnine adalah tumbuhan yang memiliki biji mematikan dengan kandungan racun seperti namanya yaitu Strychnine. Bukti dari betapa mengerikannya racun ini sendiri ditunjukkan dalam kisah Ratu Cleopatra yang meminta bawahannya untuk melakukan bunuh diri dengan memakan biji pohon Strychnine. Ia ingin mengetahui apakah biji ini adalah cara terbaik baginya untuk bunuh diri. Setelah melihat bawahannya kejang-kejang menderita kesakitan, Cleopatra mengurungkan niatnya.\n" +
                    "\n" +
                    "Alasan mengapa Cleopatra mengurungkan niatnya adalah karena memang gejala dari racun ini sangatlah terlihat mengerikan dan menyakitkan, dimulai dari kejang-kejang kuat, gemetar, muntah-muntah, kehilangan kesadaran, hingga akhirnya kematian."},
            {"14. English Yew","https://storage.googleapis.com/bbc.dosenbiologi.com/2016/01/English-Yew-1-300x196.jpg","Tanaman ini merupakan tanaman kecil yang mempunyai buah lebat seperti berry berwarna merah. English yew marupakan tanaman di dunia ini dapat membunuh manusia jika dikonsumsi dengan dosis 50 g. Efek yang ditimbulkan dari racunnya, dapat menyebabkan gagal ginjal yang berujung pada kematian tanpa ditandai ciri-ciri lainnya.\n" +
                    "\n" +
                    "Itulah beberapa tumbuhan dan tanaman mematikan. Ternyata tanaman dengan segala bentuk buah, bunga dan daun yang menarik di sekitar anda bisa saja menjadi pencabut nyawa, tanpa anda sadari. Dengan demikian, rasanya perlu kesadaran bagi anda untuk tidak sembarangan dalam mengkonsumsi maupun bermain dengan daun, buah, biji, ataupun bunga dari tanaman yang belum dikenal. Sehingga kemungkinan-kemungkinan buruk bisa anda hindari."}
    };

    public static ArrayList<Poison> getDataTumbuhan() {
        Poison tanaman = null;
        ArrayList<Poison> listt = new ArrayList<>();
        for (int i = 0; i < dataTanaman.length; i++) {
            tanaman = new Poison();
            tanaman.setNama(dataTanaman[i][0]);
            tanaman.setPhoto(dataTanaman[i][1]);
            tanaman.setDescription(dataTanaman[i][2]);
            listt.add(tanaman);
        }
        return listt;
    }

    public static String[][] datahewan = new String[][]{
            {"1. Ubur-ubur Kotak (Box Jellyfish)","https://i0.wp.com/ilmupengetahuanumum.com/wp-content/uploads/2015/10/Ubur-ubur-Kotak-Hewan-yang-paling-beracun-dan-berbisa-di-Dunia.jpg?w=499&ssl=1","Ubur-ubur Kotak atau Box Jelly fish ini merupakan Hewan yang paling berbisa di Dunia karena telah mematikan lebih dari 5000 nyawa manusia sejak tahun 1954. Racun dari bisa Ubur-ubur Kotak ini menyerang Jantung, sistem saraf dan sel-sel kulit. Korban yang terkena sengatan Ubur-ubur kotak ini akan mengalami Syok dan serangan jantung sehingga meninggal dunia sebelum mencapai tepi laut.\n" +
                    "\n" +
                    "Panjang Tentakel yaitu organ Tubuh Ubur-ubur Kotak yang memanjang dan fleksibel dapat mencapai hingga 3 meter dan memiliki sekitar 5000 sel penyengat yang mematikan. Ubur-ubur Kotak biasanya dapat ditemukan di perairan Indo-Pasific dan Australia."},
            {"2. Ular Sendok Raja (King Cobra)","https://i1.wp.com/ilmupengetahuanumum.com/wp-content/uploads/2015/10/Ular-Sendor-Raja-King-Cobra.jpg?w=500&ssl=1","Ular Sendok Raja atau King Cobra merupakan Ular yang paling mematikan di dunia ini. Satu gigitan Ular Sendok Raja dapat mematikan seorang dewasa sehat didalam jangka waktu 15 menit ataupun dapat mematikan seekor Gajah Afrika yang besar dalam jangka waktu 3 jam. Satu kali gigitan Ular King Cobra ini dapat menyuntik racun sebanyak 5 kali lipat dari ular jenis lainnya.\n" +
                    "\n" +
                    "Ular Sendok Raja juga merupakan Ular berbisa terpanjang di Dunia dengan kepanjangannya hingga 5,6 meter dan dapat menegakan badannya hingga1,8 meter.  Dikatakan Raja karena Ular King Cobra juga memangsa jenis ular lainnya. Ular King Cobra atau Ular Sendok Raja ini banyak ditemukan di kawasan perhutanan Asia Tenggara dan Asia Selatan."},
            {"3. Marbled Cone Snail","https://i1.wp.com/ilmupengetahuanumum.com/wp-content/uploads/2015/10/Siput-Marbled-Snail.jpg?w=500&ssl=1","Marbled Cone Snail adalah keluarga Siput yang sangat berbahaya, satu kali tetes bisa Marble Cone Snail dapat membunuh hingga 20 orang. Namun hingga saat ini, hanya tercatat 30 kasus kematian yang dikarenakan oleh sengatan Marbled Cone Snail. Bisa yang dikeluarkan oleh Marbled Cone Snail pada dasarnya hanya untuk menangkap mangsa.\n" +
                    "\n" +
                    "Racun Marbled Cone Snail akan menyebabkan kesulitan dalam bernafas dan gagal jantung. Hingga saat ini, belum ada obat penawar untuk racun Marble Cone Snail."},
            {"4. Blue Ringed Octopus (Gurita Berbintik Biru)","https://i1.wp.com/ilmupengetahuanumum.com/wp-content/uploads/2015/10/Gurita-Blue-Ringed.jpg?w=500&ssl=1","Blue Ringed Octopus merupakan jenis Gurita yang berbahaya karena dapat melumpuhkan manusia dengan bisanya. Satu gigitan kecil Blue Ringed Octopus yang tidak menyakitkan ini bisa menyebabkan kesulitan pernafasan, muntah, mual dan mati rasa. Hingga saat ini, belum obat penawar racun Blue Ringed Octopus. Bisa Blue Ringed Octopus dipergunakan untuk melumpuhkan mangsanya seperti udang dan kepiting.\n" +
                    "\n" +
                    "Blue Ringed Octopus dapat ditemukan di Samudera Pasifik, mulai dari Australia hingga Jepang."},
            {"5. Ikan Lepu Batu (Stonefish)","https://i1.wp.com/ilmupengetahuanumum.com/wp-content/uploads/2015/10/Ikan-Lepu-Batu-Stonefish.jpg?w=500&ssl=1","Ikan Lepu Batu atau Stonefish merupakan Ikan yang paling berbisa di dunia ini. Seperti namanya, Ikan ini berbentuk seperti Batu atau karang yang biasanya kita temukan di laut sehingga sangat sulit untuk melihatnya. Sengatan Ikan Karang dapat menyebabkan rasa sakit yang luar biasa serta kelumpuhan. Jika tidak segera diobati akan menyebabkan kematian ataupun amputasi bagian tubuh yang terkena sengatan.\n" +
                    "\n" +
                    "Stonefish yang juga disebut dengan Ikan Karang ini banyak ditemukan di perairan tropikal Samudera Pasifik dan Samudera India."},
            {"6. Kalajengking Deathstalker","https://i1.wp.com/ilmupengetahuanumum.com/wp-content/uploads/2015/10/kalajengking-deathstalker.jpg?w=500&ssl=1","Kalajengking Deathstalker merupakan jenis kalajengking yang paling berbahaya di dunia. Sengatannya dapat menyebabkan rasa sakit yang luar biasa, kejang dan demam tinggi serta koma. Pada umumnya sengatan Kalajengking Deathstalker tidak menimbulkan kematian bagi orang dewasa yang sehat. Namun akan sangat berbahaya bagi mereka yang menderita alergi, penyakit jantung maupun anak kecil dan orang tua.\n" +
                    "\n" +
                    "Kalajengking Deathstalker atau Deathstalker Scorpion dapat ditemukan di Afrika Utara dan Timur Tengah."},
            {"7. Ular Inland Taipan","https://i2.wp.com/ilmupengetahuanumum.com/wp-content/uploads/2015/10/Ular-Inland-Taipan.jpg?w=500&ssl=1","Inland Taipan merupakan Ular yang paling berbisa di Dunia ini, bisanya 200 kali lebih banyak dari ular sendok dan dapat membunuh manusia dalam waktu 40 -50 menit jika tidak dirawat segera. Ular Inland Taipan banyak ditemukan di Benua Australia, terutama dibagian Timur Australia. Meskipun memiliki Bisa yang sangat berbahaya, namun Ular Inland Taipan jarang menimbulkan kematian Manusia. Hal ini dikarena Ular Inland Taipan cenderung menghindar dari Manusia."},
            {"8. Laba-laba Brazilian Wandering","https://i1.wp.com/ilmupengetahuanumum.com/wp-content/uploads/2015/10/Laba-laba-Brazilian-Wandering.jpg?w=500&ssl=1","Menurut pengakuan Buku Rekor Dunia Guinness pada tahun 2007, Brazilian Wandering merupakan Laba-laba yang paling mematikan di dunia karena telah menyebabkan banyak kematian manusia. Cukup dengan Racun sebanyak 0.006mg dari laba-laba Brazilian Wandering ini dapat membunuh seekor Tikus. Laba-laba sangat berbahaya karena banyak dijumpai di tempat keramaian penduduk, di mobil, lemari baju maupun di sepatu. Gigitan Laba-labaBrazilian Wandering akan menimbulkan rasa sakit, peradangan dan kehilangan kendali pada otot. Jika tidak dirawat segera akan menimbulkan kematian. Untungnya, terdapat obat penawar terhadap racun laba-laba jenis ini.\n" +
                    "\n" +
                    "Laba-laba Brazilian Wandering ini banyak ditemukan di kawasan perhutanan Amazon dan Brasil."},
            {"9. Katak Panah Beracun (Poison Dart Frog)","https://i2.wp.com/ilmupengetahuanumum.com/wp-content/uploads/2015/10/Katak-Panah-Beracun.jpg?w=500&ssl=1","Katak Panah Beracun atau Poison Dart Frog merupakan Katak yang memiliki corak warna yang cerah dan terang. Dikatakan Katak Panah karena racun katak ini sering digunakan sebagai racun yang dioleskan pada ujung anak panah oleh pribumi Indian. Racun seekor Katak Panah Beracun (Poison Dart Frog) dapat membunuh 10 orang dewasa yang sehat atau sekitar 20.000 ekor tikus. Racun Katak Panah ini terdapat pada kulitnya sehingga dapat membunuh hewan lain saat mereka disentuh atau dimakan. Katak Poison Dart Frog dipercayai sebagai Hewan Vertebrate yang paling beracun di Dunia ini.\n" +
                    "\n" +
                    "Katak Panah Beracun ini dapat ditemukan di wilayah benua Amerika Tengah dan Amerika Selatan."},
            {"10. Ikan Buntal (Puffer Fish)","https://i1.wp.com/ilmupengetahuanumum.com/wp-content/uploads/2015/10/Ikan-Buntal.jpg?w=500&ssl=1","Ikan Buntal atau Puffer Fish merupakan Hewan Vertebrata paling beracun kedua di Dunia setelah Katak Panah Beracun (Poison Dart Frog). Ginjal, hati dan kulitnya mengandung racun Tetrodotoxin yang sangat berbahaya bagi yang memakannya. Hanya dengan racun 1 Ekor Ikan Buntal sudah dapat membunuh 30 orang dewasa yang sehat. Keracunan Ikan Buntal dapat menyebabkan mati rasa di bibir dan lidah, muntal, mual, sulit bernafas, pening, jantung berdetak dengan cepat, lumpuh dan kematian. Kebanyakan mereka yang keracunan Ikan Buntal akan meninggal dunia dalam waktu 4 hingga 24 jam. Namun di Jepang dan Korea, daging beberapa spesis Ikan Buntal dijadikan sebagai makanan tetapi harus disiapkan oleh juru masak yang berlisensi dan berpengalaman sehingga mereka mengetahui bagian mana yang dapat dimakan dan bagian manapula yang tidak dapat dimakan.\n" +
                    "\n" +
                    "Menurut statistik yang dipublikasikan oleh Jepang, terdapat rata-rata 6 kasus kematian dalam setahun yang dikarenakan oleh keracunan Ikan Buntal."}
    };

    public static ArrayList<Poison> getDataHewan() {
        Poison hewann = null;
        ArrayList<Poison> listt = new ArrayList<>();
        for (int i = 0; i < datahewan.length; i++) {
            hewann = new Poison();
            hewann.setNama(datahewan[i][0]);
            hewann.setPhoto(datahewan[i][1]);
            hewann.setDescription(datahewan[i][2]);
            listt.add(hewann);
        }
        return listt;
    }
}
